name: Call from original Repo
on:
 workflow_dispatch

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: kg-238/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
